spring.application.name=worker
server.port=50000

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/dist_jobs_scheduler
spring.datasource.username=${DB_USER:jobs}
spring.datasource.password=${DB_PASSWORD:jobs}
spring.datasource.hikari.maximum-pool-size=10

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest